from .animal import Animal
from .clownfish import Clownfish
from .cobra import Cobra
from .cottonmouth import Cottonmouth
from .dolphin import Dolphin
from .garter_snake import Garter_Snake
from .goat import Goat
from .human import Human
from .lemur import Lemur
from .llama import Llama
from .marlin import Marlin
from .rattlesnake import Rattlesnake
from .slimy import Slimy
from .tiger import Tiger
from .turtle import Turtle
from .whale import Whale